# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# Listening IP, default 127.0.0.1, configurable
ip=127.0.0.1

# Server port, default 5001, configurable
port=5001

# Enable HTTPS
enable_https=false

# Identity certificate, only cer format supported
ssl_certfile=etc/ssl/server.cer

# Private key file, only pem format supported
ssl_keyfile=etc/ssl/server_key.pem

# Private key file password
ssl_keyfile_password=etc/ssl/cert_pwd

# Trust certificate, only cer format supported
ssl_ca_certs=etc/ssl/trust.cer

# Revocation list
#ssl_crl_file=etc/ssl/revocationlist.crl

# Verify client certificate
verify_client=true

forwarded_allow_ips="127.0.0.1"

# Registration Center URL
agent_registry_url=http://127.0.0.1:5000

# Persistence mode: file / postgresql
persistence_mode=file
