# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

ip=127.0.0.1

port=60000

#身份证书，仅支持cer格式
ssl_certfile=etc/ssl/server.cer

#私钥文件，仅支持pem格式
ssl_keyfile=etc/ssl/server_key.pem

#私钥文件密码
ssl_keyfile_password=etc/ssl/cert_pwd

#信任证书，仅支持cer格式
ssl_ca_certs=etc/ssl/trust.cer

#校验对端证书
verify_client=true

forwarded_allow_ips="127.0.0.1"
